"""add_phone_number

Revision ID: 40b03df81b66
Revises: a1cc31a09ff8
Create Date: 2025-01-25 20:33:43.642356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

myschema:str = 'davicki'

# revision identifiers, used by Alembic.
revision: str = '40b03df81b66'
down_revision: Union[str, None] = 'a1cc31a09ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True), schema=myschema)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number', schema=myschema)
    # ### end Alembic commands ###