"""Initial migration

Revision ID: 4bb8b50ad87e
Revises: 
Create Date: 2025-01-20 15:40:00.656291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from config import settings

# revision identifiers, used by Alembic.
revision: str = '4bb8b50ad87e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

schema:str = settings.database_schema

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema=schema
    )
    op.create_index(op.f(f'ix_{schema}_users_id'), 'users', ['id'], unique=False, schema=schema)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], [f'{schema}.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema=schema
    )
    op.create_index(op.f(f'ix_{schema}_posts_id'), 'posts', ['id'], unique=False, schema=schema)
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], [f'{schema}.posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [f'{schema}.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id'),
    schema=schema
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes', schema=schema)
    op.drop_index(op.f(f'ix_{schema}_posts_id'), table_name='posts', schema=schema)
    op.drop_table('posts', schema=schema)
    op.drop_index(op.f(f'ix_{schema}_users_id'), table_name='users', schema=schema)
    op.drop_table('users', schema=schema)
    # ### end Alembic commands ###
