"""auto-vote

Revision ID: ac7051df5c01
Revises: b71a1388fb0b
Create Date: 2024-12-24 17:01:14.681545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7051df5c01'
down_revision: Union[str, None] = 'b71a1388fb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False), schema='davicki')
    op.create_foreign_key('votes_posts_fk', source_table='votes', referent_table='posts', local_cols=[
                          'post_id'], remote_cols=['id'], ondelete='CASCADE', source_schema='davicki', referent_schema='davicki')
    op.create_foreign_key('votes_users_fk', source_table='votes', referent_table='users', local_cols=[
                          'user_id'], remote_cols=['id'], ondelete='CASCADE', source_schema='davicki', referent_schema='davicki')
    op.create_primary_key(constraint_name='votes_pkey', table_name='votes', columns=['post_id', 'user_id'], schema='davicki')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes', schema='davicki')
    # ### end Alembic commands ###
