# Use the official Python base image
FROM python:3.12.7

# Update the package lists
RUN apt-get update

COPY . /app

# Set the working directory in the container
WORKDIR /app

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the python application
CMD ["python", "postgres_seed.py"]